name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: yarn install
      - name: Deploy to GH Pages
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          yarn deploy
        env:
          user_name: ${{ secrets.USERNAME }}
          user_email: ${{ secrets.EMAIL_ADDRESS }}
          github_token: ${{ secrets.ACCESS_TOKEN_FOR_GITHUB_PAGES }}
          repository: ${{ github.repository }}
      - name: Updating Domain
        run: echo "Update domain"
